image: mcr.microsoft.com/dotnet/sdk:3.1

stages:
    - build
    - test

before_script:
    - "dotnet restore"

build:
    stage: build
    tags:
        - sztaki-docker

    script:
        - "dotnet build"

test:
    stage: test
    tags:
        - sztaki-docker

    script:
        - "dotnet test"